### ISSUE TITLE
AppImage does not find included memory layouts

### ISSUE THREAD

**Issue by jimcarreer** [Dwarf-Therapist/Dwarf-Therapist#215] opened 2020-06-15 08:46 UTC
If I just download the released appimage and run it, it complains about not being able to find a memory layout until I put one in one of the locations it looked for it.  I'm currently writing a script so to install DF+DFHack+Therapist and would like to add downloading that and putting it in the proper place part of the script.  Also, is there a way to add a location to where it will look?

**Comment by jimcarreer** [comment] 2020-06-15 09:01
Found them! Sorry. For anyone looking they are:
https://github.com/Dwarf-Therapist/Dwarf-Therapist/tree/master/share/memory_layouts

**Comment by cvuchener** [comment] 2020-06-15 09:21
You should not have to download them, they are included. The issue is that I forgot to add AppRun when I updated my deploy script. Until this is fixed in a next release, you can fix the appimage yourself.

 - Download appimagetool and AppRun from https://github.com/AppImage/AppImageKit/releases
 - Extract the AppImage `./DwarfTherapist-v41.1.7-linux-x86_64.AppImage --appimage-extract` (it should extract the content in `squashfs-root`)
 - Delete `AppRun` in the extracted directory (it should be a symlink)
 - Copy AppRun-x86_64 (the one you downloaded) as AppRun in the AppImage directory
 - Use appimagetool to recreate the AppImage `appimagetool-x86_64.AppImage squashfs-root/`

**Comment by jimcarreer** [comment] 2020-06-15 12:34
@cvuchener Oh, cool, I didn't know this is a bug / actual issue. I've just stuck them in `~/.local/.../` for my purposes and Ill update my script next release to skip this step.

**Comment by cvuchener** [comment] 2020-06-15 13:16
You'll have to delete the memory layouts in ~/.local in the future or they will override those from the appimage and the updates they may contain.

**Comment by cvuchener** [comment] 2020-06-15 13:27
I reuploaded a fixed appimage. So you don't have to wait actually.

**Comment by jimcarreer** [comment] 2020-06-15 13:34
Awesome, going to update my script.

**Comment by jimcarreer** [comment] 2020-06-15 17:14
@cvuchener is there X bit you have to set on something in the appimage itself as well? I have the latest artifact downloaded, yet when I try to run it:
```
jim@jim-pc:~/games/df_47_04$ ./dt.appimage 
execv error: Permission denied
jim@jim-pc:~/games/df_47_04$ ls -alh dt.appimage 
-rwxrwxr-x 1 jim jim 29M Jun 15 09:20 dt.appimage
```

**Comment by cvuchener** [comment] 2020-06-16 07:56
Sorry, it should be good now.

**Closed** 2020-06-17 10:21 UTC
