### ISSUE TITLE
Role Calculation error when '100' cell changes

### ISSUE THREAD

**Issue by feelotraveller** [Dwarf-Therapist/Dwarf-Therapist#55] opened 2018-01-16 01:34 UTC
This bug has existed since the Splinterz versions.  When the cell that DT assigns the normalised value of 100 to changes it sometimes happens that normalised distribution becomes errant.  **The workaround is to create a new custom role, or to delete one.**

This save should demonstrate the problem: [http://dffd.bay12games.com/file.php?id=13422](http://dffd.bay12games.com/file.php?id=13422)

World was generated in DF44.02, embarked 44.03, unpaused, bug seen and saved in 44.05.  Download also includes custom roles and gridviews that will be useful (needed?) to see the problem.  Images that graphically display the problem - from DT39.1.2 (sex-icon experimental) but checked also with DT39.1.2.  Top is (what I take to be) the correct distribution, the bottom is an example of the error that arises.

<a href="https://postimg.org/image/95x5r93x7/" target="_blank"><img src="https://s17.postimg.org/9iojxfm73/nobug1.png" alt="nobug1"/></a><br/><br/>

<a href="https://postimg.org/image/wk5536e4r/" target="_blank"><img src="https://s17.postimg.org/q6g1zx98v/bug1.png" alt="bug1"/></a><br/><br/>

To get the bug with the savegame, custom roles + gridviews delete the Tanner++ custom role and then read.  (I added the Tanner++ role as a workaround to the bug.)  Adding it back and reading restores the correct distribution.  Zuglar Mistemthimshur (Carpenter+) was the intial 100 cell that subsequently changed to Urdim Adilkakdal (Herbalist).

I have heard reports of at least two other users encountering this bug.  For what it's worth they were both also using custom roles and gridviews.  I don't know if it might occur without them.  Also note that it does not always occur when the 100 cell changes but neither is it rare for it to happen.

Happy to provide further information, or the initial savegame (after embark) if these might be helpful

**Comment by cvuchener** [comment] 2018-01-16 11:03
I am not very good with statistics. DT uses different normalization methods depending on the value distribution. I cannot say it is unexpected that the values change when deleting a role.

Also Tanner++ role as provided is empty, not a copy of Tanner+. You forgot to press "Copy" or is that another case of role corruption?

**Comment by feelotraveller** [comment] 2018-01-17 09:53
It is not unexpected that values change but have a look at the distribution (in above bottom image, or after deleting Tanner++) - it is totally skewed and almost all black (i.e. 50+).  Compare this to the lack of change after adding any other role to the unbugged distribution.  I don't need to be good with statistics to know that something has gone wrong.

I'm not sure that anybody outside of splinterz had a good understanding of the statistical manipulations for the roles (although I would love to be wrong about this).  The big problem -I remember from reading on the forum- was that the vast majority of comparisons for the roles are null: most dwarfs have only a few skills and their preferences match only a very small set of those specified.  How this was dealt with while still giving useful information I do not know.  (I suspect a way into this might be to look at what was done for the smaller groupings, e.g. Armour, and at the - I hope - relatively straight-forward normalised distribution of the attributes.)

My statistics is probably no better than yours but I'm sure that your C++ is much better. :)  If you point me to the right section(s) I'll have a look on some future day when I feel like a mind-bender, dare say I won't understand much but who knows?

My current guess is that the old value of the best match (=100) is not properly 'cleared' by the program - or perhaps other values from the calculation - since this is the trigger (although only sometimes the issue arises).  Somehow this causes the recalculation to be 'benchmarked' against wrong value(s), leading the distribution to be innordinately 'squashed'.  And my hope is that if this 'leak' (yeah, I know there are surely some more 'correct' terms...) can be found and plugged then maybe a fix can be realised without needing to properly understand the 'dark magics' of the ancients.  But that is so much hot air...

If nothing else I wanted to note the issue and the workaround for others who encounter it.

[p.s. My bad on the Tanner++ (edited inital post).]

**Comment by cvuchener** [comment] 2018-10-04 09:47
There is a bug in how the median is computed and this could be the cause of this bug. I'm rewriting the rating normalization anyway in #126.

If you want to try with a fixed median, it is only a couple of line to delete:
```diff
diff --git a/src/rolecalcbase.cpp b/src/rolecalcbase.cpp
index a3c08fe..a6dc6d2 100644
--- a/src/rolecalcbase.cpp
+++ b/src/rolecalcbase.cpp
@@ -50,10 +50,8 @@ double RoleCalcBase::find_median(QVector<double> v){
     int idx_mid = (double)v.count() / 2.0f;
     double m = 0.0;
     if(v.count() % 2 == 0){
-        std::nth_element(v.begin(),v.begin()+idx_mid,v.end());
         m = 0.5 * (v.at(idx_mid)+v.at(idx_mid-1));
     }else{
-        std::nth_element(v.begin(),v.begin()+idx_mid,v.end());
         m =  v.at(idx_mid);
     }
     return m;
```

**Comment by cvuchener** [comment] 2019-05-16 09:29
With #151 merged, I think this may be fixed.

**Closed by cvuchener** 2019-05-16 09:29 UTC
